// JsFromRoutes CacheKey ae92c33fed8d4e1f57c7344d2056336c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  destroy: /* #__PURE__ */ definePathHelper('delete', '/users/sign_out'),
}
