// JsFromRoutes CacheKey a10b94b149787e127c9315054a552580
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  passthru: /* #__PURE__ */ definePathHelper('post', '/users/auth/google_oauth2'),
  googleOauth2: /* #__PURE__ */ definePathHelper('post', '/users/auth/google_oauth2/callback'),
}
