// JsFromRoutes CacheKey 24172b5e3bd5ebb0fa44c8e5e9d7fbbf
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  edit: /* #__PURE__ */ definePathHelper('get', '/users/edit'),
}
